#!/usr/bin/env bash
# commands to install and configure nginx on webserver

sudo apt-get update
sudo apt-get install nginx

sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

#testing nginx configurations

sudo nginx -t

sudo service nginx reload
