#!/usr/bin/env bash
# performing a 301 moved permanently

apt-get update
apt-get -y install nginx

echo 'Hello World!' | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/orlandoxxx-sudo permanent"

sudo sed -i "s/server_name _;/$string_for_replacement" /etc/nginx/sites-enabled/default

sudo service nginx restart
