#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.
sed -i 's/listen 80;/listen 80 default_server;/g' /etc/nginx/sites-available/default
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
