#!/bin/bash
install ufw if not already installed
sudo apt update
sudo apt install ufw -y
# Enable ufw and set default policies
sudo ufw --force enable
sudo ufw default deny incoming
sudo ufw default allow outgoing
# Allow SSH, HTTPS, and HTTP traffic
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
# Display ufw status
sudo ufw status

